### ISSUE TITLE
Missing 'models' folder.

### ISSUE THREAD

**Issue by EyalMichaeli** [lisadunlap/ALIA#8]
Firstly, Thank you for your work!
According to the README, recreating the CUB experiment is possible. However, it's not currently because the models folder is not yet pushed.
I assume that is a simple mistake and that it was just forgatten :)

**Comment by lisadunlap** [comment]
Ah you are very correct, just merged it in :)

Apologies for the delayed code released, please let me know if you run into any more errors recreating CUB!
